# Lección 20 - Concat

Mas información en el libro Python for Data Analysis Data Wrangling with Pandas

8.2 Combining and Merging Datasets

In [3]:
import numpy as np
import pandas as pd

In [4]:
array = np.arange(12).reshape((3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.concatenate([array,array],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.concatenate([array,array],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [7]:
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")
s1

a    0
b    1
dtype: Int64

In [8]:
s2 = pd.Series([3, 4, 5], index=["c", "d", "e"], dtype="Int64")
s2

c    3
d    4
e    5
dtype: Int64

In [9]:
s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")
s3

f    5
g    6
dtype: Int64

In [10]:
pd.concat([s1, s2, s3], axis="columns")

0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     3  <NA>
d  <NA>     4  <NA>
e  <NA>     5  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [11]:
s4 = pd.concat([s1, s3])
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [12]:
pd.concat([s1, s4], axis="columns", join="inner")

0  1
a  0  0
b  1  1

In [13]:
pd.concat([s1, s4], axis="columns", join="outer")

0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [ ]:
df1 = pd.DataFrame(
    np.arange(6).reshape(3, 2), index=["a", "b", "c"], columns=["one", "two"]
)
df1

one  two
a    0    1
b    2    3
c    4    5

In [19]:
df2 = pd.DataFrame(
    np.arange(4).reshape(2, 2), index=["a", "c"], columns=["three", "four"]
)
df2

three  four
a      0     1
c      2     3

In [22]:
newDb = pd.concat([df1, df2], axis="columns", keys=["level1", "level2"])
newDb

level1     level2     
     one two  three four
a      0   1    0.0  1.0
b      2   3    NaN  NaN
c      4   5    2.0  3.0

**keys** está segmentando por columna

In [23]:
newDb["level1"]

one  two
a    0    1
b    2    3
c    4    5

In [24]:
newDb["level2"]

three  four
a    0.0   1.0
b    NaN   NaN
c    2.0   3.0

Visto de otra manera, podemos trabajarlo como un objeto JSON

In [25]:
pd.concat({"level1": df1, "level2": df2}, axis="columns")

level1     level2     
     one two  three four
a      0   1    0.0  1.0
b      2   3    NaN  NaN
c      4   5    2.0  3.0